{
 "title": "Boost Stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Yearn veCRV Share",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(yearn{param=\"vecrv balance\"})",
     "legendFormat": "Yearn veCRV locked"
    },
    {
     "expr": "avg(yearn{param=\"vecrv total\"})",
     "legendFormat": "Total veCRV locked"
    }
   ]
  },
  {
   "title": "Boosties",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"boost\",vault!=\"GUSD\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "veCRV Required for Max Boost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(yearn{param=\"min vecrv\",vault!=\"GUSD\"})",
     "legendFormat": "{{vault}}"
    },
    {
     "expr": "avg(yearn{param=\"vecrv balance\"})",
     "legendFormat": "veCRV Balance"
    }
   ]
  },
  {
   "title": "Yearn veCRV Share",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(yearn{param=\"vecrv balance\"})",
     "legendFormat": "Yearn veCRV locked"
    },
    {
     "expr": "avg(yearn{param=\"vecrv total\"})",
     "legendFormat": "Total veCRV locked"
    }
   ]
  },
  {
   "title": "Max Boost Possible",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort(yearn{param=\"max boost\",vault!=\"GUSD\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  }
 ]
}