{
 "title": "V1 Vaults",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Yearn Timing",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(yearn_timing{vault!=\"registry\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Virtual Price - Rate of Increase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(yearn{param=\"virtual price\"}[2m])",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Virtual Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Virtual Price" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"virtual price\",vault=\"GUSD\"}",
     "legendFormat": "yvGUSD"
    },
    {
     "expr": "yearn{param=\"virtual price\",vault=\"curve.fi/3pool\"}",
     "legendFormat": "yv3Pool"
    },
    {
     "expr": "yearn{param=\"virtual price\",vault=\"curve.fi/y\"}",
     "legendFormat": "yvUSD"
    },
    {
     "expr": "yearn{param=\"virtual price\",vault=\"curve.fi/busd\"}",
     "legendFormat": "yvBUSD"
    },
    {
     "expr": "yearn{param=\"virtual price\",vault=\"curve.fi/sbtc\"}",
     "legendFormat": "yvSBTC"
    },
    {
     "expr": "yearn{param=\"virtual price\",vault=\"curve.fi/compound\"}",
     "legendFormat": "yvCOMP"
    }
   ]
  },
  {
   "title": "Vault Balances",
   "type": "graph",
   "description": "Yearn Vault Balances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Vault Shares " }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"vault balance\",vault=\"curve.fi/y\"}",
     "legendFormat": "yvUSD"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"DAI\"}",
     "legendFormat": "yvDAI"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"curve.fi/3pool\"}",
     "legendFormat": "yv3Pool"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"curve.fi/busd\"}",
     "legendFormat": "yvBUSD"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"USDC\"}",
     "legendFormat": "yvUSDC"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"TUSD\"}",
     "legendFormat": "yvTUSD"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"aLINK\"}",
     "legendFormat": "yvALINK"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"GUSD\"}",
     "legendFormat": "yvGUSD"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"curve.fi/compound\"}",
     "legendFormat": "yvCOMP"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"WETH\"}",
     "legendFormat": "yvWETH"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"LINK\"}",
     "legendFormat": "yvLINK"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"YFI\"}",
     "legendFormat": "yvYFI"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"curve.fi/sbtc\"}",
     "legendFormat": "yvSBTC"
    },
    {
     "expr": "yearn{param=\"vault balance\",vault=\"curve.fi/compound\"}",
     "legendFormat": "yvCOMP"
    }
   ]
  },
  {
   "title": "Boosties",
   "type": "graph",
   "description": "Boosts for the Yearn Vaults",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit", "label": "Boosties" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"boost\",vault=\"curve.fi/compound\"}",
     "legendFormat": "yvCOMP"
    },
    {
     "expr": "yearn{param=\"boost\",vault=\"curve.fi/3pool\"}",
     "legendFormat": "yv3Pool"
    },
    {
     "expr": "yearn{param=\"boost\",vault=\"curve.fi/sbtc\"}",
     "legendFormat": "yvSBTC"
    },
    {
     "expr": "yearn{param=\"boost\",vault=\"curve.fi/busd\"}",
     "legendFormat": "yvBUSD"
    },
    {
     "expr": "yearn{param=\"boost\",vault=\"curve.fi/y\"}",
     "legendFormat": "yvUSD"
    }
   ]
  },
  {
   "title": "Vault Assets Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"available\",vault=\"curve.fi/3pool\"}",
     "legendFormat": "yv3Pool"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"curve.fi/compound\"}",
     "legendFormat": "yvCOMP"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"curve.fi/busd\"}",
     "legendFormat": "yvBUSD"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"TUSD\"}",
     "legendFormat": "yvTUSD"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"USDC\"}",
     "legendFormat": "yvUSDC"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"YFI\"}",
     "legendFormat": "yvYFI"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"curve.fi/sbtc\"}",
     "legendFormat": "yvSBTC"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"LINK\"}",
     "legendFormat": "yvLINK"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"USDT\"}",
     "legendFormat": "yvUSDT"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"WETH\"}",
     "legendFormat": "yvWETH"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"GUSD\"}",
     "legendFormat": "yvGUSD"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"DAI\"}",
     "legendFormat": "yvDAI"
    },
    {
     "expr": "yearn{param=\"available\",vault=\"curve.fi/y\"}",
     "legendFormat": "yvUSD"
    }
   ]
  },
  {
   "title": "Strategy Buffer",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yearn{param=\"strategy buffer\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "CRV Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Price" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"crv price\", job=\"yearn\", vault=\"curve.fi/3pool\"}",
     "legendFormat": "Crv Price"
    }
   ]
  }
 ]
}