{
 "title": "V1 Vaults",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "How long it takes to load yearn data",
   "type": "graph",
   "description": "Yearn Timing",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(yearn_timing{instance=\"localhost:8800\", vault!=\"registry\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Share Price - Rate of Increase",
   "type": "graph",
   "description": "Rate of increase of Vault Share price. If this goes up the vaults are selling their farmed asset for more vault tokens!",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(yearn{param=\"share price\"}[2m])",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Share Price",
   "type": "graph",
   "description": "The current price of the vault's lp token, should increase steadily as vault's farmed assets are sold.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Virtual Price" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"share price\", vault!=\"GUSD\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Virtual Price - Rate of Increase",
   "type": "graph",
   "description": "Rate of Increase of the underlying curve pools' shares",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(yearn{param=\"virtual price\"}[2m])",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Virtual Price",
   "type": "graph",
   "description": "Price of the underlying curvepools",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Virtual Price" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"virtual price\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Vault Balances",
   "type": "graph",
   "description": "Yearn Vault Balances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Vault Shares " }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"vault balance\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Boosties",
   "type": "graph",
   "description": "Boosts for the Yearn Vaults",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percentunit", "label": "Boosties" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"boost\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Vault Assets Free",
   "type": "graph",
   "description": "Vaults which have liquidity that is free to withdrawal. If not show on the side you will have a fee",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sort(yearn{param=\"available\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Strategy Buffer",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(yearn{param=\"strategy buffer\"})",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "V1 - Total Assets Under Management",
   "type": "graph",
   "description": "Yearn Vault Total",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Vault Shares " }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"vault balance\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "CRV Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Price" }
   ],
   "targets": [
    {
     "expr": "yearn{param=\"crv price\", job=\"yearn\", vault=\"curve.fi/3pool\"}",
     "legendFormat": "Crv Price"
    }
   ]
  }
 ]
}