{
 "title": "V2 Vaults",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Timing",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_timing{instance=\"localhost:8801\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Price Per Share - Rate of Increase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(yearn_vault{param=\"pricePerShare\"}[2m])",
     "legendFormat": "{{vault}}",
     "panelId": 6
    }
   ]
  },
  {
   "title": "Price Per Share",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"pricePerShare\"}",
     "legendFormat": "{{vault}}",
     "panelId": 6
    }
   ]
  },
  {
   "title": "Total Assets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{instance=\"localhost:8801\",param=\"totalAssets\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total Value Locked",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "yearn_vault{param=\"tvl\"} ",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Deposit Limit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "yearn_vault{param=\"depositLimit\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Emergency Shutdown",
   "type": "stat",
   "description": "0 is no 1 is yes",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "yearn_vault{param=\"emergencyShutdown\"}",
     "legendFormat": "{{vault}}"
    }
   ]
  }
 ]
}